stages:
  - build
  - test
  - unit

build_npm:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    #- ls -la #list cmt
    - npm ci # same "npm install" but npm ci faster n using package json
    - npm run build 
    #- ls -la
  artifacts:
    paths:
      - build/

test_npm:
  image: node:22-alpine
  stage: test
  script:
    - test -f build/index.html

unit_tests:
  image: node:22-alpine
  stage: unit
  scripts:
    - npm ci
    - npm test
    